import Head from 'next/head'
import Title from '../components/Title';
//import Image from 'next/image'


export default function Home() {
  return (
		<>
			<Head>
				<title>Plant Shop</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="px-6 py-4">
			<Title>Plant Shop</Title>
			</main>
		</>
	);
}
